<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <Authors>$(AssemblyName)</Authors>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\icon.png" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Include="Assets\icon.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\VRCFaceTracking\VRCFaceTracking.Core\VRCFaceTracking.Core.csproj" />
    <ProjectReference Include="..\VRCFaceTracking\VRCFaceTracking.SDK\VRCFaceTracking.SDK.csproj" />
  </ItemGroup>

  <Target Name="PostBuild" AfterTargets="PostBuildEvent" Condition="'$(Configuration)' == 'Debug'">
      <Exec Command="copy /y &quot;$(TargetDir)PicoFacialDataModule.dll&quot; &quot;%25APPDATA%25\VRCFaceTracking\CustomLibs&quot;" />
      <Exec Command="copy /y &quot;$(TargetDir)PicoFacialDataModule.pdb&quot; &quot;%25APPDATA%25\VRCFaceTracking\CustomLibs&quot;" />
  </Target>

</Project>
